##### General #####
set -g escape-time 50
set -g mouse on
bind-key m if -F "#{?mouse,1,0}" "set -g mouse off \; display-message 'Mouse mode: off'" "set -g mouse on \; display-message 'Mouse mode: on'"
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Terminal settings
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g allow-passthrough on
set -g default-shell /bin/zsh
set -ga update-environment "DISPLAY WAYLAND_DISPLAY XAUTHORITY"

# Tokyo Night theme pane borders
set -g pane-border-style "fg=#2A2F41"
set -g pane-active-border-style "fg=#7aa2f7"

# Copy mode style
set -g mode-style "bg=#7aa2f7,fg=#c0caf5"

# Status line general style
set -g status-position bottom
set -g status-bg '#2A2F41'
set -g status-fg '#c0caf5'
set -g window-status-format ""
set -g window-status-current-format ""

# Left status
set -g status-left-length 150
set -g status-left "#[bg=#7aa2f7]#[fg=#2A2F41][#S] #I:#W  #[bg=#2A2F41]#[fg=#7aa2f7]#[fg=#c0caf5]"

# Right status
set -g status-right-length 100
set -g status-right "#[bg=#2A2F41]#[fg=#7aa2f7]#[bg=#7aa2f7]#[fg=#2A2F41] #{pane_current_path} "

##### Clipboard #####
set -g set-clipboard on

##### Reload #####
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded!"
