on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bats xclip xvfb
      - name: Run tests
        timeout-minutes: 5
        run: xvfb-run -a bats tests
